# Generated by Django 5.2.1 on 2025-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='userName',
            field=models.CharField(default='myname', max_length=100),
        ),
    ]
