# Generated by Django 5.2.1 on 2025-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='accessNames',
            field=models.JSONField(default=list),
        ),
    ]
