# Generated by Django 5.2.1 on 2025-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_image_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
